USE [master]
GO

/****** Object:  Database [TweetDb]    Script Date: 6/22/2022 6:07:00 PM ******/
CREATE DATABASE [TweetDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TweetDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TweetDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TweetDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TweetDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TweetDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TweetDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TweetDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TweetDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TweetDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TweetDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TweetDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TweetDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TweetDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TweetDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TweetDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TweetDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TweetDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TweetDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TweetDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TweetDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TweetDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TweetDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TweetDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TweetDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TweetDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TweetDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TweetDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TweetDb] SET RECOVERY FULL 
GO

ALTER DATABASE [TweetDb] SET  MULTI_USER 
GO

ALTER DATABASE [TweetDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TweetDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TweetDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TweetDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TweetDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TweetDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TweetDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TweetDb] SET  READ_WRITE 
GO

